version: 2

defaults: &defaults
  docker:
    - image: angular/ngcontainer:latest
  working_directory: ~/workspace

attach_options: &attach_options
  at: ~/workspace

# Jobs
jobs:
  install:
    <<: *defaults
    steps:
      # Checkout, Download and cache dependencies
      - checkout
      - restore_cache:
          key: latest-dependencies-{{ checksum "yarn.lock" }}
      # Install dependencies
      - run: yarn install --frozen-lockfile --non-interactive
      - save_cache:
          key: latest-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - 'node_modules'
      - persist_to_workspace:
          root: ~/workspace
          paths: .

  build:
    <<: *defaults
    steps:
      - run: yarn build
      - run: xvfb-run -a yarn test
      - store_artifacts:
          path: ~/workspace/dist

  deploy:
    <<: *defaults
    steps:
      - attach_workspace: *attach_options
      - run:
          name: Deploying to GitHub packages
          command: |
            # CIRCLE_TAG indicates whether the job runs for the tag (as opposed to: the commit on the branch)
            if [ -z "${CIRCLE_TAG}" ]; then
              echo "Skipping deployment. This build job runs for a branch."
              exit 0
            fi
            echo "Deploying ${CIRCLE_TAG}..."
            yarn deploy

# Workflows
workflows:
  version: 2
  ci_workflow:
    jobs:
    - build
    - deploy:
        requires:
          - build
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /v.*/
