version: 2
jobs:
  build:
    docker:
    - image: angular/ngcontainer:latest
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          key: master-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: master-{{ checksum "yarn.lock" }}
          paths:
          - ~/app/node_modules
      - run: yarn build
      - run: xvfb-run -a yarn test
      - store_artifacts:
          path: ~/app/dist

workflows:
  version: 2
  build:
    jobs:
    - build
  
