version: 2

defaults: &defaults
  docker:
    - image: angular/ngcontainer:latest
  working_directory: ~/workspace

attach_options: &attach_options
  at: ~/workspace

# Jobs
jobs:
  install:
    <<: *defaults
    steps:
      # Checkout, Download and cache dependencies
      - checkout
      - restore_cache:
          key: latest-dependencies-{{ checksum "yarn.lock" }}
      # Install dependencies
      - run: yarn install --frozen-lockfile --non-interactive
      - save_cache:
          key: latest-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - 'node_modules'
      - persist_to_workspace:
          root: ~/workspace
          paths: .

  build:
    <<: *defaults
    steps:
      - attach_workspace: *attach_options
      - run: yarn build
      - run: xvfb-run -a yarn test
      - store_artifacts:
          path: ~/workspace/dist

  deploy:
    <<: *defaults
    steps:
      - attach_workspace: *attach_options
      # Deploy from CircleCI to GitHub Pages
      # https://circleci.com/blog/deploying-documentation-to-github-pages-with-continuous-integration/
      - add_ssh_keys:
          fingerprints:
            - "e6:42:4d:0d:a4:8a:32:08:9c:0d:2f:40:4e:91:28:d9"
      - run:
          name: Add SSH Host Key for github.com
          command: |
            # https://github.com/openmicroscopy/devspace/issues/38#issuecomment-211515244
            ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: Deploy to GitHub packages
          command: |
            # CIRCLE_TAG indicates whether the job runs for the tag (as opposed to: the commit on the branch)
            if [ -z "${CIRCLE_TAG}" ]; then
              echo "Skipping deployment. This build job runs for a branch."
              exit 0
            fi
            git config --global user.email "dherges@users.noreply.github.com"
            git config --global user.name "dherges"
            echo "Deploying ${CIRCLE_TAG}..."
            yarn deploy

# Workflows
workflows:
  version: 2
  ci_workflow:
    jobs:
    - install:
        filters:
          tags:
            only: /v.*/
    - build:
        requires:
          - install
        filters:
          branches:
            ignore: /master/
          tags:
            only: /v.*/
    - deploy:
        requires:
          - build
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /v.*/
